### PR TITLE
New post: all about that buildpack

### PR DESCRIPTION
**Pull request by npupatk**

### CODE REVIEW

**Comment by LaureMFischer** [comment]
This is great! I don't know much about buildpacks and I think this is a really good intro. :+1:

**Comment by zcotter** [comment]
:+1:

**Comment by npupatk** [comment]
cool! thanks for reviewing :)

**Comment by primalcodes** [comment]
NICE!  This was similar to what I needed to do (tried) for the dev-days react-rails demo!  Great info :+1:

**Pull request merged**
