### PR TITLE
The Value of Feedback blog post

### PR DESCRIPTION
**Pull request by pherefordATK**

### CODE REVIEW

**Comment by LaureMFischer** [comment]
:+1: great post! Only suggestion would be to maybe add a little more color around what an article page looks like, why it needs to be more unstructured, etc. as compared to just a recipe. Just a thought, since maybe some people would be reading this for the tech insights but may not be familiar with the content on our site.

**Comment by pherefordATK** [comment]
good call!!

**Comment by zcotter** [comment]
Awesome post! You did a great job concisely explaining how the tool works and connecting it back to the feedback process you went through.
I was going to say there is a lot going on at once - you are talking about your awesome and super technical web edit tool AND how the feedback cycle works/its benefits AND the importance of tooling. As a reader, I'm probably only smart enough to think about one or two of those things in depth at the same time. But since this is targeted for a developer audience, I actually think it makes sense to talk about the feedback cycle with an engaging technical example like this rather than from a feature development point of view. :+1:

**Comment by pherefordATK** [comment]
Thanks guys!! Gonna do a quick spell check and publish.

**Pull request merged**
